lab06/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tienda/', include('tienda.urls')),
    path('admin/', admin.site.urls),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import CategoriaListView, ProductoListView, ProductoDetailView, ProductoCreateView, ProductoUpdateView, ProductoDeleteView

app_name = 'tienda'
urlpatterns = [
    path('', views.index, name='index'),
    path('producto/<int:producto_id>/', views.producto, name='producto'),
    path('categoria/<int:categoria_id>/', views.productos_por_categoria, name='productos_por_categoria'),

    path('api/categorias/', CategoriaListView.as_view(), name='categoria-list'),
    path('api/productos/', ProductoListView.as_view(), name='producto-list'),
    path('api/productos/<int:producto_id>/', ProductoDetailView.as_view(), name='producto-detail'),
    path('api/productos/create/', ProductoCreateView.as_view(), name='producto-create'),
    path('api/productos/<int:producto_id>/update/', ProductoUpdateView.as_view(), name='producto-update'),
    path('api/productos/<int:producto_id>/delete/', ProductoDeleteView.as_view(), name='producto-delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    pub_date = models.DateTimeField('fecha de registro',auto_now=True)
    imagen = models.ImageField(upload_to='categorias/', null=True, blank=True)
    
    def __str__(self):
        return self.nombre


class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6,decimal_places=2)
    stock = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    imagen = models.ImageField(upload_to='productos/', null=True, blank=True)
    
    def __str__(self):
        return self.nombre

tienda/views.py
from django.shortcuts import get_object_or_404, render
from .models import Categoria, Producto
from rest_framework.views import APIView
from rest_framework.response import Response
from .Serializer import CategoriaSerializer, ProductoSerializer



# Create your views here.
def index(request):
    product_list = Producto.objects.order_by('nombre')[:6]
    categorias = Categoria.objects.all()
    context = {
        'product_list': product_list,
        'categorias': categorias,  # Asegúrate de incluir las categorías en el contexto
    }
    return render(request, 'index.html', context)

def producto (request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    categorias= Categoria.objects.all()
    return render(request, 'producto.html', {'producto': producto
                                             , 'categorias': categorias})


def listar_categoria(request):
    categorias = Categoria.objects.all()
    return render(request, 'layout.html', {'categorias': categorias})
    


def productos_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, id=categoria_id)
    productos = Producto.objects.filter(categoria=categoria)
    context = {
        'productos': productos,
        'categoria': categoria,  
        'categorias': Categoria.objects.all(),  
    }
    return render(request, 'productos_por_categoria.html', context)


class CategoriaListView(APIView):   
    def get(self, request):
        categorias = Categoria.objects.all()
        serializer = CategoriaSerializer(categorias, many=True)
        return Response(serializer.data)


class ProductoListView(APIView):
    def get(self, request):
        productos = Producto.objects.all()
        serializer = ProductoSerializer(productos, many=True)
        return Response(serializer.data)

class ProductoDetailView(APIView):
    def get(self, request, producto_id):
        producto = get_object_or_404(Producto, pk=producto_id)
        serializer = ProductoSerializer(producto)
        return Response(serializer.data)

class ProductoCreateView(APIView):
    def post(self, request):
        serializer = ProductoSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(serializer.errors, status=400)
                        

class ProductoUpdateView(APIView):
    def put(self, request, producto_id):
        producto = get_object_or_404(Producto, pk=producto_id)
        serializer = ProductoSerializer(producto, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=400)
    
    
class ProductoDeleteView(APIView):
    def delete(self, request, producto_id):
        producto = get_object_or_404(Producto, pk=producto_id)
        producto.delete()
        return Response(status=204)

tienda/templates/index.html
{% extends "layout.html" %}
{% block content %}
<!-- Block Content -->
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
      {% for categoria in categorias %}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
      {% endfor %}
  </ol>
  <div class="carousel-inner" role="listbox">
      {% for categoria in categorias %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img class="d-block img-fluid" src="{{ categoria.imagen.url }}" alt="{{ categoria.nombre }}">
          </div>
      {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
  </a>
</div>

<div class="row">
    {% for prod in product_list %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="producto/{{ prod.id }}/">
                <img class="card-img-top" src="{{ prod.imagen.url }}" alt="{{ prod.nombre }}">
            </a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="producto/{{ prod.id }}/">{{ prod.nombre }}</a>
                </h4>
                <h5>S/ {{ prod.precio }}</h5>
                <p class="card-text">Categoría: {{ prod.categoria.nombre }}</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- /Block Content -->
{% endblock %}

tienda/templates/layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shop Homepage</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/shop.css' %}" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">
          <h1 class="my-4">La real tienda</h1>
          <div class="list-group">

              <!-- Mostrar el contenido completo de categorias -->
            <ul>
                {% for categoria in categorias %}
                <li><a href="{% url 'tienda:productos_por_categoria' categoria.id %}">{{ categoria.nombre }}</a></li>

                {% empty %}
                    <li>No hay categorías disponibles</li>
                {% endfor %}
            </ul>
          </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
            {% block content %}{% endblock %}          
        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

tienda/templates/producto.html
{% extends "layout.html" %}
<ul>
    {% for categoria in categorias %}
        <li>{{ categoria.nombre }}</li>
    {% empty %}
        <li>No hay categorías disponibles</li>
    {% endfor %}
</ul>

{% block content %}
<h1>{{ producto.nombre }}</h1>
<img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}">
<p>Precio: S/ {{ producto.precio }}</p>
<p>Categoría: {{ producto.categoria.nombre }}</p>
<p>{{ producto.descripcion }}</p>
{% endblock %}

tienda/templates/productos_por_categoria.html
{% extends "layout.html" %}

{% block content %}
<h1>Productos en la categoría: {{ categoria_nombre }}</h1>

<div class="row">
    {% for producto in productos %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="{% url 'tienda:producto' producto.id %}">
                <img class="card-img-top" src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}">
            </a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="{% url 'tienda:producto' producto.id %}">{{ producto.nombre }}</a>
                </h4>
                <h5>S/ {{ producto.precio }}</h5>
                <p class="card-text">Categoría: {{ producto.categoria.nombre }}</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
        </div>
    </div>
    {% empty %}
    <p>No hay productos en esta categoría.</p>
    {% endfor %}
</div>
{% endblock %}

<ul>
    {% for categoria in categorias %}
        <li>{{ categoria.nombre }}</li>
    {% empty %}
        <li>No hay categorías disponibles</li>
    {% endfor %}
</ul>